### ISSUE TITLE
tconvert() not supporting leap seconds

### ISSUE THREAD

**Issue by litingxiao** [gwpy/gwpy#1021]
It's a very small issue and I can get around it without using tconvert(). But just wanted to report the error messages that I obtained today:

  File "asd_O2.py", line 148, in <module>
    print 'Processing data from ' + str(tconvert(gpsstart)) + ' to ' + str(tconvert(gpsend))
  File "/usr/lib/python2.7/site-packages/gwpy/time/_tconvert.py", line 88, in tconvert
    return from_gps(gpsordate)
  File "/usr/lib/python2.7/site-packages/gwpy/time/_tconvert.py", line 195, in from_gps
    date = Time(sec, format='gps', scale='utc').datetime
  File "/usr/lib64/python2.7/site-packages/astropy/time/core.py", line 1104, in __getattr__
    value = tm._shaped_like_input(tm._time.to_value(parent=tm))
  File "/usr/lib64/python2.7/site-packages/astropy/time/formats.py", line 609, in to_value
    .format((iy, im, id, ihr, imin, isec, ifracsec)))
ValueError: Time (array(2016, dtype=int32), array(12, dtype=int32), array(31, dtype=int32), array(23, dtype=int32), array(59, dtype=int32), array(60, dtype=int32), array(0, dtype=int32)) is within a leap second but datetime does not support leap seconds

**Comment by duncanmmacleod** [comment]
@litingxiao, can you print the argument (`gpsstart`, or `gpsend`) so that I can try and reproduce?

**Comment by litingxiao** [comment]
@duncanmmacleod Yes, it's as follows: 

> python
> from gwpy.time import tconvert
> tconvert(1167264017)

Error: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/time/_tconvert.py", line 89, in tconvert
    return from_gps(gpsordate)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/time/_tconvert.py", line 196, in from_gps
    date = Time(sec, format='gps', scale='utc').datetime
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/time/core.py", line 1135, in __getattr__
    value = tm._shaped_like_input(tm._time.to_value(parent=tm))
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/time/formats.py", line 619, in to_value
    .format((iy, im, id, ihr, imin, isec, ifracsec)))
ValueError: Time (array(2016, dtype=int32), array(12, dtype=int32), array(31, dtype=int32), array(23, dtype=int32), array(59, dtype=int32), array(60, dtype=int32), array(0, dtype=int32)) is within a leap second but datetime does not support leap seconds

**Comment by duncanmmacleod** [comment]
@litingxiao, I'm sorry for the extraordinary delay in getting to this. I have finally rediscovered this issue and put some thought into it. Unfortunately, the issue is fundamental, in that the `gwpy.time.tconvert` method converts to and from `datetime.datetime` objects in python, which simply don't support leap seconds in any way.

So, you can't use `tconvert()` and expect it to work with leap seconds. However, you can work around this using something like

```python
>>> from astropy.time import Time
>>> print(Time(1167264017, format="gps", scale="utc").iso)
'2016-12-31 23:59:60.000'
```
