### ISSUE TITLE
HTTP error 400: Bad Request

### ISSUE THREAD

**Issue by GregoryAshton** [gwpy/gwpy#1083]
Updating to gwpy 0.14, the commands

```python
data = TimeSeries.get('H1:GDS-CALIB_STRAIN', 1126259446, 1126259478)
```

and

```python
data = TimeSeries.find('L1:ISI-GND_STS_ITMY_Z_DQ', 'Jan 1 2016', 'Jan 1 2016 01:00')
```

Both failed. Here is the traceback.

```python
Traceback (most recent call last):
  File "/home/gregory.ashton/anaconda3/envs/bilby/bin/bilby_pipe_generation", line 11, in <module>
    load_entry_point('bilby-pipe==0.0.4', 'console_scripts', 'bilby_pipe_generation')()
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/bilby_pipe-0.0.4-py3.7.egg/bilby_pipe/data_generation.py", line 479, in main
    data = DataGenerationInput(args, unknown_args)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/bilby_pipe-0.0.4-py3.7.egg/bilby_pipe/data_generation.py", line 87, in __init__
    self.create_data(args)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/bilby_pipe-0.0.4-py3.7.egg/bilby_pipe/data_generation.py", line 114, in create_data
    self._set_interferometers_from_data()
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/bilby_pipe-0.0.4-py3.7.egg/bilby_pipe/data_generation.py", line 351, in _set_interferometers_from_data
    data = self._get_data(det, self.channel_type, self.start_time, end_time)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/bilby_pipe-0.0.4-py3.7.egg/bilby_pipe/data_generation.py", line 408, in _get_data
    data = self._gwpy_get(det, channel, start_time, end_time)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/bilby_pipe-0.0.4-py3.7.egg/bilby_pipe/data_generation.py", line 431, in _gwpy_get
    channel, start_time, end_time, verbose=True
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/timeseries/core.py", line 623, in get
    verbose=verbose, allow_tape=allow_tape, **kwargs)[str(channel)]
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/timeseries/core.py", line 1374, in get
    **kwargs)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/timeseries/core.py", line 1249, in find
    allow_tape=allow_tape)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/io/datafind.py", line 327, in wrapped
    return func(*args, **kwargs)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/io/datafind.py", line 593, in find_best_frametype
    connection=connection, host=host, port=port)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/io/datafind.py", line 327, in wrapped
    return func(*args, **kwargs)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/io/datafind.py", line 463, in find_frametype
    connection=connection)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/io/datafind.py", line 327, in wrapped
    return func(*args, **kwargs)
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwpy/io/datafind.py", line 611, in find_types
    return sorted(connection.find_types(observatory, match=match),
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwdatafind/http.py", line 246, in find_types
    typelist = set(self.get_json(url))
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwdatafind/http.py", line 116, in get_json
    response = self._request_response('GET', url, **kwargs).read()
  File "/home/gregory.ashton/anaconda3/envs/bilby/lib/python3.7/site-packages/gwdatafind/http.py", line 96, in _request_response
    response.getheaders(), response.fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

I rolled back to version 0.12 (indicated as stable in the docs) and the issue was resolved. I'm not sure where to start digging to see what is going on.

**Comment by duncanmmacleod** [comment]
@GregoryAshton, apologies for the extraordinary delay in getting to this, this is an upstream issue in `gwdatafind`, but I believe that the impact on gwpy was mitigated in 2057e7bfa9222bd63fc1cfb80deff7e7a2563bd1, can you confirm whether you are still seing this with the latest release?

**Comment by GregoryAshton** [comment]
Testing with 0.15 everything works: there are no errors. Thanks.
