### ISSUE TITLE
"General failure" within TimeSeries.psd(..., method="lal_median")

### ISSUE THREAD

**Issue by reedessick** [gwpy/gwpy#1090]
I've run into the following error when attempting to compute a PSD using LAL as a backend (`method="lal_median"`). I've run into the same error (copied below) with the following versions

  * gwpy 0.12.2 and 0.14.0
  * scipy 1.2.1
  * lal 6.19.2

*Note*, @duncanmmacleod cannot reproduce this on his mac when using gwpy-0.14.2 and lal-6.19.2.

On the LHO cluster, I find that using scipy (`method="median"`) instead of lal with gwpy-0.14.0 and scipy-1.2.1 gives me a PSD, but I still get errors with `method="lal_median"`.

```
>>> source /home/reed.essick/DetChar/setup.sh
>>> python
>>> import gwpy
>>> gwpy.__version__
u'0.12.2'
>>> import scipy
>>> scipy.__version__
'1.2.1'
>>> import lal
>>> lal.__version__
'6.19.2'
>>> from gwpy import timeseries
>>> data = timeseries.TimeSeries.get('H1:GDS-CALIB_STRAIN', 1238250255.000, 1238250768.000, frametype='H1_llhoft').resample(4096)
>>> data.crop(1238250255.289, 1238250767.289).psd(4., 2., window='hann', method='median')
XLAL Error - XLALCreateREAL8FFTPlan (RealFFT_source.c:120): Generic failure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reed.essick/DetChar/opt/lib/python2.7/site-packages/gwpy-0.12.2-py2.7.egg/gwpy/timeseries/timeseries.py", line 308, in psd
    overlap=overlap, window=window, **kwargs)
  File "/home/reed.essick/DetChar/opt/lib/python2.7/site-packages/gwpy-0.12.2-py2.7.egg/gwpy/signal/fft/ui.py", line 236, in wrapped_func
    normalize_fft_params(data, kwargs=kwargs, func=method_func)
  File "/home/reed.essick/DetChar/opt/lib/python2.7/site-packages/gwpy-0.12.2-py2.7.egg/gwpy/signal/fft/ui.py", line 142, in normalize_fft_params
    kwargs['plan'] = generate_fft_plan(nfft, dtype=series.dtype)
  File "/home/reed.essick/DetChar/opt/lib/python2.7/site-packages/gwpy-0.12.2-py2.7.egg/gwpy/signal/fft/lal.py", line 86, in generate_fft_plan
```

**Comment by alurban** [comment]
@reedessick, what do you get if you use `method='lal_median_mean'`?

**Comment by reedessick** [comment]
@alurban, no idea. Don't have time to test this myself, but hopefully I haven't accidentally destroyed my environment on LHO and you can use it if you want to chase this further.

**Comment by alurban** [comment]
@reedessick, I reproduced your error from the environment in `/home/reed.essick/DetChar/`. However, if I use the /cvmfs `ligo-py37` conda environment, which has the latest versions of everything:

```python
In [1]: import gwpy                                                                                                               
    
In [2]: gwpy.__version__                                                                                                          
Out[2]: '0.14.2'

In [3]: import scipy                                                                                                              

In [4]: scipy.__version__                                                                                                         
Out[4]: '1.2.1'

In [5]: import lal                                                                                                                

In [6]: lal.__version__                                                                                                           
Out[6]: '6.19.2'
```

Then all the following commands work fine:

```python
In [7]: from gwpy.timeseries import TimeSeries                                                                                    

In [8]: data = TimeSeries.get('H1:GDS-CALIB_STRAIN', 1238250255.000, 1238250768.000, frametype='H1_llhoft').resample(4096)        

In [9]: data.crop(1238250255.289, 1238250767.289).psd(4., 2., window='hann', method='lal_median_mean')                            
/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py37/lib/python3.7/site-packages/gwpy/signal/spectral/_lal.py:214: UserWarning: Data array is the wrong size for the correct number of averages given the input parameters. The trailing 8192 samples will not be used in this calculation.
  % (size - required))
Out[9]: 
<FrequencySeries([4.61013675e-47, 4.78464169e-47, 5.16764638e-47,
                  ..., 2.21593663e-47, 2.42679266e-47,
                  1.71525889e-47]
                 unit=Unit("1 / Hz"),
                 f0=<Quantity 0. Hz>,
                 df=<Quantity 0.25 Hz>,
                 epoch=<Time object: scale='utc' format='gps' value=1238250255.2888184>,
                 name='H1:GDS-CALIB_STRAIN',
                 channel=<Channel("H1:GDS-CALIB_STRAIN", 16384.0 Hz) at 0x7f8172475780>,
                 frequencies=None)>

In [10]: data.crop(1238250255.289, 1238250767.289).psd(4., 2., window='hann', method='lal_median')                                
Out[10]: 
<FrequencySeries([4.69842055e-47, 4.69868808e-47, 5.12148918e-47,
                  ..., 2.22767062e-47, 2.44030558e-47,
                  1.80572741e-47]
                 unit=Unit("1 / Hz"),
                 f0=<Quantity 0. Hz>,
                 df=<Quantity 0.25 Hz>,
                 epoch=<Time object: scale='utc' format='gps' value=1238250255.2888184>,
                 name='H1:GDS-CALIB_STRAIN',
                 channel=<Channel("H1:GDS-CALIB_STRAIN", 16384.0 Hz) at 0x7f8172475780>,
                 frequencies=None)>

In [11]: data.crop(1238250255.289, 1238250767.289).psd(4., 2., window='hann', method='median')                                    
Out[11]: 
<FrequencySeries([4.41777685e-41, 2.19432948e-41, 9.97867655e-47,
                  ..., 4.45627725e-47, 4.88131635e-47,
                  1.41571088e-47]
                 unit=Unit("1 / Hz"),
                 f0=<Quantity 0. Hz>,
                 df=<Quantity 0.25 Hz>,
                 epoch=<Time object: scale='utc' format='gps' value=1238250255.288818>,
                 name='H1:GDS-CALIB_STRAIN',
                 channel=<Channel("H1:GDS-CALIB_STRAIN", 16384.0 Hz) at 0x7f8172475780>,
                 frequencies=None)>
```

My only suggestion is maybe try updating to gwpy-0.14.2 and see if that fixes your problem.

**Comment by reedessick** [comment]
Thanks, @duncanmmacleod pointed out that gwpy-0.14.2 works (see this issue's original description) when I was first chasing this.

The current solution adopted for the DQR is to use `method="median"` which Laura Nuttall has confirmed will not mess up anything else in her implementation (@duncanmmacleod's first suggestion). @duncanmmacleod also asked me to document this particular oddity here because he wanted to figure out why older versions didn't work, so this is more bookkeeping than anything else.
