### ISSUE TITLE
timeseries.write("file.gwf") LAL_DETECTOR.keys is missing?

### ISSUE THREAD

**Issue by matxil** [gwpy/gwpy#1094]
Hi, 

After reading in (succesfully) an HDF5 file, I then want to save it as GWF file. With other hd5 files this normally works, but with this particular file, when I make this call: 
`  timeseries.write( "new_file.gwf" )`
I get the error: 
```
File ".../local/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/lalframe.py", line 177, in write
idx = list(lalutils.LAL_DETECTORS.keys()).index(series.channel.ifo)
ValueError: None is not in list
```
I can only assume that somehow the timeseries is lacking some information (although I can print out correctly the t0 and duration attributes).

**Comment by duncanmmacleod** [comment]
Can you post enough code to reproduce the error on another machine, so I can investigate? Thanks.

**Comment by matxil** [comment]
Ok, I will first post the code, and then how I use it and the output. 
CODE: 
```
from gwpy.timeseries import TimeSeries
import sys
def ConvertFile (in_filename, in_format, in_channel, out_format):
    if (in_format == "hdf5" ): 
        try:
            print "calling ts =  TimeSeries.read(", in_filename,", format=", in_format, ")"
            timeseries = TimeSeries.read(in_filename, format=in_format)
        except Exception as e:
            print "Error loading timeseries, from file: ", in_filename, " ", e
    elif ( in_format == "gwf" ):
        try:
            print "calling ts =  TimeSeries.read(", in_filename,", channel=", in_channel, ")"
            timeseries = TimeSeries.read(in_filename, channel=in_channel)
        except Exception as e:
            print "Error reading frame, from file: ", in_filename, " ", e
    if out_format == 'hdf5':
        try:
            timeseries.write( "new_file.hdf5", "hdf5" )
        except Exception as e:
            print "Error in saving timeseries: ", e
    elif out_format == 'gwf':
        print "timeseries: ", timeseries.t0, " ", timeseries.t0 + timeseries.duration
        timeseries.write( "new_file.gwf" )

filename = raw_input("Give filename:   ")
in_format = raw_input("Give input format:   ")
in_whatever = None
if (in_format == "gwf"):
    in_whatever = raw_input("Give input channel:   ")
out_format = raw_input("Give output format:   ")

ConvertFile (filename, in_format, in_whatever, out_format )
```

The way I use it, is, I first read a HDF5 file, convert it to a GWF file. Then I read that new GWF file and translate it to a new HDF5 file. Then I read this new HDF5 file and try to translate it - again - into a GWF file: 

```
$ python convert_GWPY.py 
Give filename:   H1_1126259446_1126259478.hdf5
Give input format:   hdf5
Give output format:   gwf
calling ts =  TimeSeries.read( H1_1126259446_1126259478.hdf5 , format= hdf5 )
timeseries:  1126259446.0 s   1126259478.0 s

$ python convert_GWPY.py 
Give filename:   new_file.gwf
Give input format:   gwf
Give input channel:   Strain
Give output format:   hdf5
calling ts =  TimeSeries.read( new_file.gwf , channel= Strain )

$ python convert_GWPY.py 
Give filename:   new_file.hdf5
Give input format:   hdf5
Give output format:   gwf
calling ts =  TimeSeries.read( new_file.hdf5 , format= hdf5 )
timeseries:  1126259446.0 s   1126259478.0 s
Traceback (most recent call last):
  File "convert_GWPY.py", line 38, in <module>
    ConvertFile (filename, in_format, in_whatever, out_format )
  File "convert_GWPY.py", line 27, in ConvertFile
    timeseries.write( "new_file.gwf" )
  File "/home/mkolstein/GW_repository/GRAV_WAVES/gwpy_0_12/other_env/local/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 289, in write
    return io_registry.write(self, target, *args, **kwargs)
  File "/home/mkolstein/GW_repository/GRAV_WAVES/gwpy_0_12/other_env/local/lib/python2.7/site-packages/astropy/io/registry.py", line 581, in write
    writer(data, *args, **kwargs)
  File "/home/mkolstein/GW_repository/GRAV_WAVES/gwpy_0_12/other_env/local/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/__init__.py", line 384, in write_
    return writer(*args, **kwargs)
  File "/home/mkolstein/GW_repository/GRAV_WAVES/gwpy_0_12/other_env/local/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/__init__.py", line 349, in write_timeseries
    return write_timeseriesdict({None: series}, *args, **kwargs)
  File "/home/mkolstein/GW_repository/GRAV_WAVES/gwpy_0_12/other_env/local/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/__init__.py", line 339, in write_timeseriesdict
    name=name, run=run)
  File "/home/mkolstein/GW_repository/GRAV_WAVES/gwpy_0_12/other_env/local/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/lalframe.py", line 177, in write
    idx = list(lalutils.LAL_DETECTORS.keys()).index(series.channel.ifo)
ValueError: None is not in list
```

**Comment by duncanmmacleod** [comment]
@matxil, apologies for the extensive delay in responding to this. I was able to reproduce this, and will try and work up a fix.

In the mean time, if you are able to install [`python-ldas-tools-framecpp`](https://anaconda.org/conda-forge/python-ldas-tools-framecpp), gwpy will prefer this GWF backend and you will not see the error.

**Comment by matxil** [comment]
Hi Duncan, 

Thanks for your reply. I tried using pip to install [`python-ldas-tools-framecpp`] but that didn't work. Do I have to use conda for this? Or can I just update GWpy now that you fixed it?
Cheers, 

Machiel

> @matxil, apologies for the extensive delay in responding to this. I was able to reproduce this, and will try and work up a fix.
> 
> In the mean time, if you are able to install [`python-ldas-tools-framecpp`](https://anaconda.org/conda-forge/python-ldas-tools-framecpp), gwpy will prefer this GWF backend and you will not see the error.
