### ISSUE TITLE
Could not find the request epoch

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#1103]
When trying to retrieve data from our (NDS1) server with this script, I get a `Could not find the request epoch` error:

```python
from gwpy.timeseries import TimeSeries
from matplotlib import pyplot as plt

data = TimeSeries.fetch(start="yesterday", end="now", channel="G2:PEM-BASE_PART_300", host="pt-firefly", port=8088)
plt.plot(data)
plt.show()
```

```
(gwpy-dev) sean@totoro /tmp $ python tmp.py
Traceback (most recent call last):
  File "tmp.py", line 4, in <module>
    data = TimeSeries.fetch(start="yesterday", end="now", channel="G2:PEM-BASE_PART_300", host="pt-firefly", port=8088)
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/gwpy/timeseries/core.py", line 379, in fetch
    allow_tape=allow_tape, type=type, dtype=dtype)[str(channel)]
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/gwpy/timeseries/core.py", line 1187, in fetch
    series_class=cls.EntryClass).crop(start, end)
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/gwpy/io/nds2.py", line 351, in wrapped_func
    return func(*args, **kwargs)
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/gwpy/timeseries/io/nds2.py", line 117, in fetch
    unique=True)
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/gwpy/io/nds2.py", line 351, in wrapped_func
    return func(*args, **kwargs)
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/gwpy/io/nds2.py", line 380, in wrapped_func
    return func(*args, **kwargs)
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/gwpy/io/nds2.py", line 366, in wrapped_func
    return func(*args, **kwargs)
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/gwpy/io/nds2.py", line 449, in find_channels
    connection.set_epoch(*epoch)
  File "/home/sean/Workspace/anaconda/envs/gwpy-dev/lib/python3.7/site-packages/nds2.py", line 3351, in set_epoch
    return _nds2.connection_set_epoch(self, *args)
RuntimeError: Low level daq error occured [1]: Unspecified error
Could not find the request epoch
```

This error occurs both on 0.14.2 (conda) and 0.15.0 (pip).

It appears the connection to the NDS server is taking place, from the server logs:

```
[Mon Apr 29 14:48:33 2019] connection on port 38943 from 10.117.14.225;
fd=42 req_tp n_gds_servers=16; node[0]=33 tpnum[0]=30183
decimation flag=1
[Mon Apr 29 14:48:33 2019] connection on fd 42 closed
[Mon Apr 29 14:48:33 2019] connection on port 38943 from 10.117.14.225;
fd=41 [Mon Apr 29 14:48:33 2019] ->37: version
[Mon Apr 29 14:48:33 2019] ->37: revision
[Mon Apr 29 14:48:33 2019] ->37: quit
[Mon Apr 29 14:48:33 2019] connection on fd 41 closed
```

However it appears `gwpy` or the `python-nds2-client` is deciding to quit after asking the server for its version and revision.

With `nds_query`, I can successfully retrieve a list of channels from the same machine running the above script:

```
> nds_query -1 -n pt-firefly -p 8088 -l
...huge list of channels...
```

**Comment by duncanmmacleod** [comment]
@SeanDS, apologies for the delay in looking at this. Is there any chance of getting access to a machine that can connect to the nds1 host so that I can look at this further? I'm not particularly familiar with the nds1 connection object and its limitations, so trial-and-error debugging is the best way to make progress.

**Comment by SeanDS** [comment]
Just emailed you some credentials... thanks
