### ISSUE TITLE
ModuleNotFoundError with Channel.query()

### ISSUE THREAD

**Issue by mouzaalmualla** [gwpy/gwpy#1260]
Hello!

When trying to use Channel.query(), I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/gwemopt1/lib/python3.7/site-packages/gwpy/detector/channel.py", line 430, in query
    debug=debug)
  File "/opt/anaconda3/envs/gwemopt1/lib/python3.7/site-packages/gwpy/detector/channel.py", line 794, in query
    return cis.query(name, use_kerberos=use_kerberos, debug=debug)
  File "/opt/anaconda3/envs/gwemopt1/lib/python3.7/site-packages/gwpy/detector/io/cis.py", line 62, in query
    reply = _get(url, use_kerberos=use_kerberos, debug=debug)
  File "/opt/anaconda3/envs/gwemopt1/lib/python3.7/site-packages/gwpy/detector/io/cis.py", line 82, in _get
    from ligo.org import request
ModuleNotFoundError: No module named 'ligo.org'

I'm not sure what ligo.org is here? This is the code that produces this error:

`from gwpy.detector import Channel`
`chan = Channel.query('L1:IMC-F_OUT_DQ')`

**Comment by duncanmmacleod** [comment]
Hi, @mouzaalmualla, thanks for your report. You should be able to update to gwpy-2.0.0, and install the relevant third-part module using conda-forge:

```shell
conda install -c conda-forge "gwpy>=2.0.0" ciecplib
```

Please let me know if that solves your problem.

[gwpy 2.0.0 includes an update to the `Channel.query` internals to use the new `ciecplib` module]

**Comment by mouzaalmualla** [comment]
Yes it does! Thank you.
