### ISSUE TITLE
Unable to read in "time_slide" ligolw table through `EventTable.read()`

### ISSUE THREAD

**Issue by myNameIsPatrick** [gwpy/gwpy#1264]
This should hopefully give a minimal example with a ligolw-formatted file with a time slide table contained within.

```
>>> EventTable.read("path/to/ligolw_file.xml.gz", tablename="time_slide")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/table/table.py", line 241, in read
    return io_read_multi(vstack, cls, source, *args, **kwargs)
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/io/mp.py", line 92, in read_multi
    output = mp_utils.multiprocess_with_queues(
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/utils/mp.py", line 123, in multiprocess_with_queues
    return list(map(_inner, inputs))
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/utils/mp.py", line 118, in _inner
    return func(x)
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/io/mp.py", line 121, in _read_single_file
    return fobj, io_read(cls, fobj, *args, **kwargs)
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/astropy/io/registry.py", line 523, in read
    data = reader(*args, **kwargs)
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/table/io/utils.py", line 67, in wrapper
    tab = func(*args, **kwargs)
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/table/io/ligolw.py", line 395, in read_table
    return Table(read_ligolw_table(source, tablename=tablename, **read_kw),
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/astropy/table/table.py", line 436, in __init__
    data = data.__astropy_table__(self.__class__, copy, **kwargs)
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/table/io/ligolw.py", line 160, in to_astropy_table
    arr = _get_column(llwtable, colname)
  File "/home/patrick.godwin/.conda/envs/idq-dev/lib/python3.8/site-packages/gwpy/table/io/ligolw.py", line 186, in _get_column
    return getattr(llwtable, get_)()
TypeError: get_time_slide_id() missing 1 required positional argument: 'offsetdict'
```

I'm not sure why it's trying to call `get_time_slide_id()` as it appears to be an extra method that's only defined for the time slide table.

**Comment by myNameIsPatrick** [comment]
This is not a real fix, but commenting out the part of the internal function that grabs ligolw columns by accessing `get_{}` methods (https://github.com/gwpy/gwpy/blob/master/gwpy/table/io/ligolw.py#L182-L186) appears to do the trick:

```
>>> EventTable.read("path/to/ligolw_file.xml.gz", tablename="time_slide")
<EventTable length=6>
instrument  offset process_id time_slide_id
   str2    float64   int64        int64    
---------- ------- ---------- -------------
        V1 0.31415          4             0
        H1     0.0          4             0
        L1 0.62831          4             0
        V1     0.0          4             1
        H1     0.0          4             1
        L1     0.0          4             1
```

**Comment by duncanmmacleod** [comment]
@myNameIsPatrick, are you able to link me to an actual LIGO_LW XML file that contains a `time_slide` table, so that I can test a fix?

**Comment by myNameIsPatrick** [comment]
@duncanmmacleod, will do. I've contacted you off list with a path to one since it contains LIGO data.
