### ISSUE TITLE
TimeSeries.fetch with a Channel object

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#1288]
Specifying a `Channel` object in a call to `TimeSeries.fetch` results in a `KeyError`, despite the documentation specifying that the channel argument can be a `Channel`:

```
>>> print(TimeSeries.fetch.__doc__)
Fetch data from NDS

        Parameters
        ----------
        channel : `str`, `~gwpy.detector.Channel`
            the data channel for which to query

        start : `~gwpy.time.LIGOTimeGPS`, `float`, `str`
            GPS start time of required data,
            any input parseable by `~gwpy.time.to_gps` is fine

        end : `~gwpy.time.LIGOTimeGPS`, `float`, `str`
            GPS end time of required data,
            any input parseable by `~gwpy.time.to_gps` is fine

        host : `str`, optional
            URL of NDS server to use, if blank will try any server
            (in a relatively sensible order) to get the data

        port : `int`, optional
            port number for NDS server query, must be given with `host`

        verify : `bool`, optional, default: `False`
            check channels exist in database before asking for data

        scaled : `bool`, optional
            apply slope and bias calibration to ADC data, for non-ADC data
            this option has no effect

        connection : `nds2.connection`, optional
            open NDS connection to use

        verbose : `bool`, optional
            print verbose output about NDS progress, useful for debugging;
            if ``verbose`` is specified as a string, this defines the
            prefix for the progress meter

        type : `int`, optional
            NDS2 channel type integer

        dtype : `type`, `numpy.dtype`, `str`, optional
            identifier for desired output data type

>>> from gwpy.timeseries import TimeSeries
>>> from gwpy.detector import Channel
>>> channel = Channel("G2:SQL-MIXER_OOL_OUT_DQ")
>>> data = TimeSeries.fetch(channel, "2020-12-07 12:00", "2020-12-07 12:05", host="pt-firefly", port=8088)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sean/Workspace/miniconda/envs/base/lib/python3.8/site-packages/gwpy/timeseries/core.py", line 376, in fetch
    return cls.DictClass.fetch(
KeyError: 'G2:SQL-MIXER_OOL_OUT_DQ'
>>> data = TimeSeries.fetch(channel.name, "2020-12-07 12:00", "2020-12-07 12:05", host="pt-firefly", port=8088)
>>> import gwpy
>>> gwpy.__version__
'2.0.2'
```

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1288, please join us on gitlab to continue your contribution!
