### ISSUE TITLE
Error writing channel list to file

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#1291]
The function that produces INI format files for channels seems to be looking for a non-existent property of `Channel`, `group`:

```python
from gwpy.detector import Channel, ChannelList

channel = Channel("G2:SQL-MIXER_OOL_OUT_DQ")
channels = ChannelList()
channels.append(channel)

channels.write("tmp.ini")
```

```
Traceback (most recent call last):
  File "tmp.py", line 7, in <module>
    channels.write("tmp.ini")
  File "/home/sean/Workspace/miniconda/envs/sbruco/lib/python3.8/site-packages/gwpy/detector/channel.py", line 636, in write
    return io_registry.write(self, target, *args, **kwargs)
  File "/home/sean/Workspace/miniconda/envs/sbruco/lib/python3.8/site-packages/astropy/io/registry.py", line 563, in write
    writer(data, *args, **kwargs)
  File "/home/sean/Workspace/miniconda/envs/sbruco/lib/python3.8/site-packages/gwpy/detector/io/clf.py", line 142, in write_channel_list_file
    return write_channel_list_file(channels, fobj)
  File "/home/sean/Workspace/miniconda/envs/sbruco/lib/python3.8/site-packages/gwpy/detector/io/clf.py", line 146, in write_channel_list_file
    group = channel.group
AttributeError: 'Channel' object has no attribute 'group'
```

**Comment by SeanDS** [comment]
Seems to be a problem with omega scan formatted channel list files too.
The tests don't seem to check the generation of files from channel lists created via the Python API, only the reading and re-writing/re-reading of [hard-coded channel list file strings](https://github.com/gwpy/gwpy/blob/6feb4f4485c86801c1708c3517bdba6c34fb3b76/gwpy/detector/tests/test_channel.py).

**Comment by SeanDS** [comment]
If I manually add a `group` attribute to each channel in the `ChannelList`, I then get the following error:

```
    Traceback (most recent call last):
      File "/home/sean/Workspace/repos/sbruco/sbruco/__main__.py", line 357, in cli
        search.run(ncores)
      File "/home/sean/Workspace/repos/sbruco/sbruco/sbruco.py", line 185, in run
        channels = set(self.search_channels())
      File "/home/sean/Workspace/repos/sbruco/sbruco/sbruco.py", line 140, in search_channels
        channels.write(self.search_channels_path)
      File "/home/sean/Workspace/miniconda/envs/sbruco/lib/python3.8/site-packages/gwpy/detector/channel.py", line 636, in write
        return io_registry.write(self, target, *args, **kwargs)
      File "/home/sean/Workspace/miniconda/envs/sbruco/lib/python3.8/site-packages/astropy/io/registry.py", line 563, in write
        writer(data, *args, **kwargs)
      File "/home/sean/Workspace/miniconda/envs/sbruco/lib/python3.8/site-packages/gwpy/detector/io/clf.py", line 142, in write_channel_list_file
        return write_channel_list_file(channels, fobj)
      File "/home/sean/Workspace/miniconda/envs/sbruco/lib/python3.8/site-packages/gwpy/detector/io/clf.py", line 149, in write_channel_list_file
        for param, value in channel.params.items():
    AttributeError: 'Channel' object has no attribute 'params'
```

**Comment by duncanmmacleod** [comment]
@SeanDS, what are you trying to achieve? I ask that not to question you using this particular part of the API, only to work out the best way to fix the (clearly broken, at best badly documented) API to meet your needs.

**Comment by SeanDS** [comment]
I'm building an application on top of gwpy ([bruco](https://git.ligo.org/gabriele-vajente/bruco)-like) and want it to be able to cache channel searches retrieved via `ChannelList.query_nds2` to the file system between runs to avoid having to fetch the same sets of channels every time.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1291, please join us on gitlab to continue your contribution!
