### ISSUE TITLE
TypeError when using seaborn after importing gwpy

### ISSUE THREAD

**Issue by mj-will** [gwpy/gwpy#1311]
Importing `gwpy` and then calling certain plotting functions in `seaborn` raises an error:

```
Traceback (most recent call last):
  File "bilby_example.py", line 55, in <module>
    result = bilby.run_sampler(outdir=outdir, label=label, resume=True, plot=True,
  File "/nfshome/store03/users/michael.williams/git_repos/bilby/bilby/core/sampler/__init__.py", line 185, in run_sampler
    result = sampler.run_sampler()
  File "/nfshome/store03/users/michael.williams/git_repos/bilby/bilby/core/sampler/nessai.py", line 142, in run_sampler
    out.run(save=True, plot=self.plot)
  File "/nfshome/store03/users/michael.williams/git_repos/nessai/nessai/flowsampler.py", line 128, in run
    plot.plot_live_points(self.posterior_samples,
  File "/nfshome/store03/users/michael.williams/git_repos/nessai/nessai/plot.py", line 56, in plot_live_points
    fig.map_offdiag(sns.scatterplot, hue=hue,
  File "/home/michael.williams/.conda/envs/nessai/lib/python3.8/site-packages/seaborn/axisgrid.py", line 1311, in map_offdiag
    self.map_lower(func, **kwargs)
  File "/home/michael.williams/.conda/envs/nessai/lib/python3.8/site-packages/seaborn/axisgrid.py", line 1281, in map_lower
    self._map_bivariate(func, indices, **kwargs)
  File "/home/michael.williams/.conda/envs/nessai/lib/python3.8/site-packages/seaborn/axisgrid.py", line 1465, in _map_bivariate
    self._plot_bivariate(x_var, y_var, ax, func, **kws)
  File "/home/michael.williams/.conda/envs/nessai/lib/python3.8/site-packages/seaborn/axisgrid.py", line 1505, in _plot_bivariate
    func(x=x, y=y, **kwargs)
  File "/home/michael.williams/.conda/envs/nessai/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/michael.williams/.conda/envs/nessai/lib/python3.8/site-packages/seaborn/relational.py", line 820, in scatterplot
    p.plot(ax, kwargs)
  File "/home/michael.williams/.conda/envs/nessai/lib/python3.8/site-packages/seaborn/relational.py", line 651, in plot
    points = ax.scatter(*args, **kws)
TypeError: scatter() takes from 3 to 4 positional arguments but 5 were given
```

## Versions

I'm using `python==3.8` with the following versions of the relevant packages:

```
numpy==1.19.2
seaborn==0.11.1
matplotlib==3.3.4
gwpy==2.0.2
```

## Code to reproduce

The following code snippet works if  `gwpy` is not imported but fails once it is imported.
```
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import gwpy

x = np.random.randn(100, 2)
df = pd.DataFrame(data=x)

fig = sns.PairGrid(df, corner=True, diag_sharey=False)
fig.map_diag(plt.hist)
fig.map_offdiag(sns.scatterplot)
```

**Comment by mj-will** [comment]
Tagging @duncanmmacleod
