### ISSUE TITLE
EventTable.read fails if first entry in cache has no triggers

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#1334]
Evidently it's possible for Omicron to produce ligolw and hdf5 files with no triggers. This corner case occurs when 

- Reading from a list of files in a cache
- The first file in the cache is valid but has 0 triggers and subsequent files have some triggers
- The read selects columns, I think the first selected column has to be numeric

The error seems to be in astropy merging tables with incompatible or non-existant columns.

The hdf5 error looks like:
```  File "/Users/areeda/opt/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'peak'
python-BaseException
```
The ligolw error looks like
```TableMergeError: The 'peak' columns have incompatible types: ['object', 'float64', 'float64', 'float64']```

Two demos are attached:
[trig-read-demo.zip](https://github.com/gwpy/gwpy/files/6503807/trig-read-demo.zip)

**Comment by eagoetz** [comment]
Ping @duncanmmacleod this remains an open issue. Summary page jobs fail because, for example, `gwsumm` calls `table = EventTable.read(cache, **kwargs)` with:
```
cache = ['/home/detchar/triggers/L1/ASC_X_TR_B_NSUM_OUT_DQ_OMICRON/13608/L1-ASC_X_TR_B_NSUM_OUT_DQ_OMICRON-1360887925-2400.xml.gz', '/home/detchar/triggers/L1/ASC_X_TR_B_NSUM_OUT_DQ_OMICRON/13608/L1-ASC_X_TR_B_NSUM_OUT_DQ_OMICRON-1360886245-240.xml.gz', '/home/detchar/triggers/L1/ASC_X_TR_B_NSUM_OUT_DQ_OMICRON/13608/L1-ASC_X_TR_B_NSUM_OUT_DQ_OMICRON-1360892245-1680.xml.gz', '/home/detchar/triggers/L1/ASC_X_TR_B_NSUM_OUT_DQ_OMICRON/13608/L1-ASC_X_TR_B_NSUM_OUT_DQ_OMICRON-1360890325-1920.xml.gz', '/home/detchar/triggers/L1/ASC_X_TR_B_NSUM_OUT_DQ_OMICRON/13608/L1-ASC_X_TR_B_NSUM_OUT_DQ_OMICRON-1360886485-1440.xml.gz', '/home/detchar/triggers/L1/ASC_X_TR_B_NSUM_OUT_DQ_OMICRON/13608/L1-ASC_X_TR_B_NSUM_OUT_DQ_OMICRON-1360893925-1240.xml.gz']
```
and
```
kwargs = {'format': 'ligolw', 'selection': [], 'tablename': 'sngl_burst', 'use_numpy_dtypes': True, 'verbose': False, 'columns': ['peak', 'peak_frequency', 'bandwidth', 'snr', 'duration', 'central_freq']}
```

The traceback looks like this:
```
Traceback (most recent call last):
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/astropy/table/operations.py", line 1398, in _vstack
    col = col_cls.info.new_like(cols, n_rows, metadata_conflicts, out_name)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/astropy/table/column.py", line 453, in new_like
    attrs = self.merge_cols_attributes(cols, metadata_conflicts, name,
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/astropy/utils/data_info.py", line 721, in merge_cols_attributes
    out['dtype'] = metadata.common_dtype(cols)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/astropy/utils/metadata.py", line 64, in common_dtype
    raise tme
astropy.utils.metadata.MergeConflictError: Arrays have incompatible types ['float64', 'object', 'float64', 'float64', 'float64', 'float64']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwsumm/__main__.py", line 871, in <module>
    main()
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwsumm/__main__.py", line 845, in main
    tab.process(config=config, nds=args.nds,
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwsumm/tabs/etg.py", line 262, in process
    super(EventTriggerTab, self).process(*args, **kwargs)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwsumm/tabs/data.py", line 376, in process
    self.process_state(state, config=config, nproc=nproc,
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwsumm/tabs/etg.py", line 271, in process_state
    super(EventTriggerTab, self).process_state(state, *args, **kwargs)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwsumm/tabs/data.py", line 551, in process_state
    get_triggers(channel, etg, state.active, config=config,
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwsumm/triggers.py", line 244, in get_triggers
    trigs = read_cache(segcache, SegmentList([segment]), etg,
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwsumm/triggers.py", line 439, in read_cache
    table = EventTable.read(cache, **kwargs)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwpy/table/table.py", line 235, in read
    return io_read_multi(vstack, cls, source, *args, **kwargs)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/gwpy/io/mp.py", line 101, in read_multi
    return flatten(out)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/astropy/table/operations.py", line 651, in vstack
    out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/astropy/table/operations.py", line 1402, in _vstack
    raise TableMergeError("The '{}' columns have incompatible types: {}"
astropy.table.np_utils.TableMergeError: The 'peak' columns have incompatible types: ['float64', 'object', 'float64', 'float64', 'float64', 'float64']
```

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1334, please join us on gitlab to continue your contribution!
