### ISSUE TITLE
UnitConversionError during TimeSeries.append() usage

### ISSUE THREAD

**Issue by mikelovskij** [gwpy/gwpy#148]
When using spectrogram.append() or timeseries.append() i often get an exception saying Valueerror: TimeSeries units do not match: None vs undef " or "Timeseries units do not match: None vs undef". 
The issue seems to be caused by line [441 of gwpy/series.py](https://github.com/gwpy/gwpy/blob/master/gwpy/data/series.py#L441) where a value without unit is copied in a valued value. The issue seems to be easily solved by changing 
``` python
            try:
                self.xindex[-other.shape[0]:] = other.xindex.value
``` 
with 
``` python
            try:
                self.xindex[-other.shape[0]:] = other.xindex
```

**Comment by duncanmmacleod** [comment]
The exception `TimeSeries units do not match` is raised by line [309 of gwpy/series.py](https://github.com/gwpy/gwpy/blob/master/gwpy/data/series.py#L309). Can you paste the full traceback of the error you are seeing?

**Comment by mikelovskij** [comment]
Hi, sorry but for some reason i pasted the wrong exception. Here is the full traceback 
``` python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 586, in callit
    func(*args)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 143, in _on_timer
    TimerBase._on_timer(self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 1273, in _on_timer
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 910, in _step
    still_going = Animation._step(self, *args)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 769, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 788, in _draw_next_frame
    self._draw_frame(framedata)
  File "build/bdist.linux-x86_64/egg/dataviewer/data.py", line 134, in _draw_frame
    self.refresh()
  File "build/bdist.linux-x86_64/egg/dataviewer/timeseries.py", line 151, in refresh
    ts.append(t2, pad=self.buffer.pad, gap=self.buffer.gap)
  File "/home/mikelovskij/.local/lib/python2.7/site-packages/gwpy/data/series.py", line 441, in append
    self.xindex[-other.shape[0]:] = other.xindex.value
  File "/usr/local/lib/python2.7/dist-packages/astropy/units/quantity.py", line 860, in __setslice__
    self.view(np.ndarray).__setslice__(i, j, self._to_own_unit(value))
  File "/usr/local/lib/python2.7/dist-packages/astropy/units/quantity.py", line 1087, in _to_own_unit
    raise exc
UnitConversionError: '' (dimensionless) and 's' (time) are not convertible
```
