### ISSUE TITLE
TimeSeriesDict.get hangs

### ISSUE THREAD

**Issue by js01** [gwpy/gwpy#1548]
When trying to build documentation, I found TimeSeriesDict.get hangs, causing examples to hang.

Reproducible example from examples/coherence.py:

```
from gwpy.timeseries import TimeSeriesDict
data = TimeSeriesDict.get(['H1:GDS-CALIB_STRAIN', 'H1:PEM-CS_ACC_PSL_PERISCOPE_X_DQ'], 1126260017, 1126260017 + 10)
```

As far as I can tell this hangs indefinitely.  Keyboard interrupt shows an exception in nds2.
```

daq_recv_id: Error in read: Interrupted system call
Error reading writerID in daq_recv_block
ERRNO: read_server_response_wait: Timed out: errno: 62 - Timer expiredTraceback (most recent call last):
  File "/home/j/miniconda3/lib/python3.9/site-packages/gwpy/timeseries/io/nds2.py", line 157, in fetch
    for buffers in connection.iterate(int(seg[0]), int(seg[1]), names):
  File "/home/j/miniconda3/lib/python3.9/site-packages/nds2.py", line 1368, in iterate
    return _nds2.connection_iterate(self, *args)
RuntimeError: Low level daq error occured [1]: Unspecified error


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/j/miniconda3/lib/python3.9/site-packages/gwpy/timeseries/core.py", line 1374, in get
    return cls.fetch(channels, start, end, pad=pad, scaled=scaled,
  File "/home/j/miniconda3/lib/python3.9/site-packages/gwpy/timeseries/core.py", line 1136, in fetch
    return cls.fetch(channels, start, end, host=host_,
  File "/home/j/miniconda3/lib/python3.9/site-packages/gwpy/timeseries/core.py", line 1173, in fetch
    return fetch(channels, istart, iend, connection=connection,
  File "/home/j/miniconda3/lib/python3.9/site-packages/gwpy/io/nds2.py", line 361, in wrapped_func
    return func(*args, **kwargs)
  File "/home/j/miniconda3/lib/python3.9/site-packages/gwpy/timeseries/io/nds2.py", line 157, in fetch
    for buffers in connection.iterate(int(seg[0]), int(seg[1]), names):
KeyboardInterrupt
```

I appreciate this may not be a problem with gwpy itself.

**Comment by duncanmmacleod** [comment]
I think I reported the relevant upstream issue here: https://git.ligo.org/computing/helpdesk/-/issues/2756 (requires LIGO.ORG authentication). If that get's resolved I will attempt to reproduce your failure and will close as appropriate.

**Comment by duncanmmacleod** [comment]
@js01, the upstream issue has been resolved and your example code returns in ~10 seconds for me. Please confirm and close.

**Comment by js01** [comment]
Yes, it no longer hangs.
