### ISSUE TITLE
Reading TimeSeries from empty Cache raises IndexError

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#163]
Reading a `TimeSeries` from an empty `glue.lal.Cache` or `list` raises an `IndexError`:

```python
>>> from gwpy.timeseries import TimeSeries
>>> TimeSeries.read([], 'test', format='gwf')
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/registry.py", line 332, in read
    data = reader(*args, **kwargs)
  File "/Users/duncan/Library/Python/2.7/lib/python/site-packages/gwpy-0.1a10.dev833-py2.7.egg/gwpy/utils/deps.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/duncan/Library/Python/2.7/lib/python/site-packages/gwpy-0.1a10.dev833-py2.7.egg/gwpy/timeseries/io/gwf/__init__.py", line 128, in read_timeseries
    return read_timeseriesdict(source, [channel], *args, **kwargs)[channel]
  File "/Users/duncan/Library/Python/2.7/lib/python/site-packages/gwpy-0.1a10.dev833-py2.7.egg/gwpy/timeseries/io/gwf/__init__.py", line 122, in read_timeseriesdict
    return reader(source, *args, **kwargs)
  File "/Users/duncan/Library/Python/2.7/lib/python/site-packages/gwpy-0.1a10.dev833-py2.7.egg/gwpy/utils/deps.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/duncan/Library/Python/2.7/lib/python/site-packages/gwpy-0.1a10.dev833-py2.7.egg/gwpy/timeseries/io/gwf/framecpp.py", line 134, in read_timeseriesdict
    frametype = CacheEntry.from_T050017(filelist[0]).description
IndexError: list index out of range
```

While the error type is not an issue, the error cause is likely to confuse many users. The frametype setting should except an `IndexError` to allow the data reader to raise an exception (possibly `ValueError` or `IndexError`) with an error that mentions the empty cache.

**Comment by duncanmmacleod** [comment]
The following patch might be a nice solution

```diff
diff --git a/gwpy/timeseries/io/gwf/__init__.py b/gwpy/timeseries/io/gwf/__init_
index caa298b..e5367fb 100644
--- a/gwpy/timeseries/io/gwf/__init__.py
+++ b/gwpy/timeseries/io/gwf/__init__.py
@@ -109,6 +109,9 @@ def register_gwf_io_library(library, package='gwpy.timeserie
     def read_timeseriesdict(source, *args, **kwargs):
         """Read `TimeSeriesDict` from GWF source
         """
+        if isinstance(source, list) and not len(source):
+            raise ValueError("Cannot read from empty source %s"
+                             % type(source).__name__)
         # use multiprocessing or padding
         nproc = kwargs.pop('nproc', 1)
         pad = kwargs.pop('pad', None)
```
