### ISSUE TITLE
set_epoch fails for gwpy Plot objects

### ISSUE THREAD

**Issue by eagoetz** [gwpy/gwpy#1642]
Matplotlib scale.py seems unhappy about the `epoch` keyword argument. An example is below
```python
>>> import gwpy
>>> range_plot = gwpy.plot.Plot(figsize=(12, 6))
>>> ax = range_plot.gca()
>>> ax.set_epoch(1371239645)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/gwpy/lib/python3.9/site-packages/gwpy/plot/axes.py", line 219, in set_epoch
    return self.set_xscale(scale, epoch=epoch)
  File "/opt/miniconda3/envs/gwpy/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 74, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/opt/miniconda3/envs/gwpy/lib/python3.9/site-packages/matplotlib/axis.py", line 810, in _set_axes_scale
    ax._axis_map[name]._set_scale(value, **kwargs)
  File "/opt/miniconda3/envs/gwpy/lib/python3.9/site-packages/matplotlib/axis.py", line 767, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "/opt/miniconda3/envs/gwpy/lib/python3.9/site-packages/matplotlib/scale.py", line 714, in scale_factory
    return scale_cls(axis, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'epoch'
```

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1642, please join us on gitlab to continue your contribution!
