### ISSUE TITLE
`TimeSeries.get` discrepancy between `gwpy` 2.1.5 and 3.0.5

### ISSUE THREAD

**Issue by EthanMarx** [gwpy/gwpy#1655]
The following code
```python
from gwpy.timeseries import TimeSeries
TimeSeries.get("H1:DCS-CALIB_STRAIN_CLEAN_C01", 1244704476.0, 1244724476.0)
```
produces the following full traceback using `gwpy=3.0.5`:

```
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/io/datafind.py:400: UserWarning: failed to read channels for type 'H1_HOFT_C01': No Table of Contents object for Stream:
  warnings.warn(
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/io/datafind.py:400: UserWarning: failed to read channels for type 'H1_HOFT_C00': No Table of Contents object for Stream:
  warnings.warn(
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/io/datafind.py:400: UserWarning: failed to read channels for type 'H1_HOFT_CLEAN_SUB60HZ_C01': No Table of Contents object for Stream:
  warnings.warn(
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/io/datafind.py:400: UserWarning: failed to read channels for type 'SenseMonitor_CAL_H1_M': No Table of Contents object for Stream:
  warnings.warn(
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/io/datafind.py:400: UserWarning: failed to read channels for type 'SenseMonitor_hoft_H1_M': No Table of Contents object for Stream:
  warnings.warn(
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py:1144: NDSWarning: failed to fetch data for H1:DCS-CALIB_STRAIN_CLEAN_C01 in interval [1244704476.0, 1244724476.0): unique NDS2 channel match not found for 'H1:DCS-CALIB_STRAIN_CLEAN_C01'
  warnings.warn(
Error in write(): Connection refused
Error in write(): Connection refused
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py:1144: NDSWarning: failed to fetch data for H1:DCS-CALIB_STRAIN_CLEAN_C01 in interval [1244704476.0, 1244724476.0): Failed to establish a connection[INFO: Error occurred trying to write to socket]
  warnings.warn(
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py:1144: NDSWarning: failed to fetch data for H1:DCS-CALIB_STRAIN_CLEAN_C01 in interval [1244704476.0, 1244724476.0): unique NDS2 channel match not found for 'H1:DCS-CALIB_STRAIN_CLEAN_C01'
  warnings.warn(
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py:1144: NDSWarning: failed to fetch data for H1:DCS-CALIB_STRAIN_CLEAN_C01 in interval [1244704476.0, 1244724476.0): unique NDS2 channel match not found for 'H1:DCS-CALIB_STRAIN_CLEAN_C01'
  warnings.warn(
Error in write(): Connection refused
Error in write(): Connection refused
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py:1144: NDSWarning: failed to fetch data for H1:DCS-CALIB_STRAIN_CLEAN_C01 in interval [1244704476.0, 1244724476.0): Failed to establish a connection[INFO: Error occurred trying to write to socket]
  warnings.warn(
/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py:1144: NDSWarning: failed to fetch data for H1:DCS-CALIB_STRAIN_CLEAN_C01 in interval [1244704476.0, 1244724476.0): unique NDS2 channel match not found for 'H1:DCS-CALIB_STRAIN_CLEAN_C01'
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py", line 596, in get
    return cls.DictClass.get(
  File "/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py", line 1379, in get
    return cls.fetch(channels, start, end, pad=pad, scaled=scaled,
  File "/home/ethan.marx/miniconda3/envs/aframe-test/lib/python3.9/site-packages/gwpy/timeseries/core.py", line 1169, in fetch
    raise RuntimeError(err)
RuntimeError: Cannot find all relevant data on any known server. Try again using the verbose=True keyword argument  to see detailed failures.
```

However, using `gwpy=2.1.5` it queries the data fine. 
These times correspond to segments following the `DCS-ANALYSIS_READY_C01:1` state flag

For completeness, here are the environment files used to build each `gwpy` version:
```yaml
name: gwpy-2.1.5
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gwpy=2.1.5
  - python-ldas-tools-framecpp<3.0.0
  - python-nds2-client
```

```yaml
name: gwpy-3.0.5
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gwpy=3.0.5
  - python-ldas-tools-framecpp
  - python-nds2-client
```

**Comment by EthanMarx** [comment]
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
astropy                   5.3.1            py39h0f8d45d_0    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotli-python             1.0.9            py39h5a03fae_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39he91dace_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0            py39h7633fee_0    conda-forge
cryptography              41.0.3           py39hd4f0224_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cyrus-sasl                2.1.27               h54b06d7_7    conda-forge
dqsegdb2                  1.1.4              pyhd8ed1ab_0    conda-forge
fonttools                 4.42.0           py39hd1e30aa_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gwdatafind                1.1.3              pyhd8ed1ab_0    conda-forge
gwosc                     0.7.1              pyhd8ed1ab_0    conda-forge
gwpy                      3.0.5              pyhd8ed1ab_0    conda-forge
h5py                      3.9.0           nompi_py39h680ca82_101    conda-forge
hdf5                      1.14.1          nompi_h4f84152_100    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
igwn-auth-utils           0.4.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib-resources       6.0.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39hf939315_1    conda-forge
krb5                      1.21.1               h659d440_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
ldas-tools-al             2.6.7                h27087fc_4    conda-forge
ldas-tools-framecpp       3.0.2                ha63f0ea_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ligo-segments             1.4.0            py39hb9d737c_4    conda-forge
ligotimegps               2.0.1                      py_0    conda-forge
matplotlib-base           3.7.1            py39he190548_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
nds2-client               0.16.8               h93a0877_3    conda-forge
numpy                     1.25.2           py39h6183b62_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pillow                    10.0.0           py39haaeba84_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.0.3          py39h389d5f1_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.16          h2782a2a_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-ldas-tools-al      2.6.10           py39hf939315_2    conda-forge
python-ldas-tools-framecpp 3.0.0            py39hdd85611_0    conda-forge
python-nds2-client        0.16.12          py39h4661b88_3    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pyyaml                    6.0              py39hb9d737c_5    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
safe-netrc                1.0.0                      py_0    conda-forge
scipy                     1.11.1           py39h6183b62_0    conda-forge
scitokens                 1.7.4              pyhd8ed1ab_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.65.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unicodedata2              15.0.0           py39hb9d737c_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
```

**Comment by duncanmmacleod** [comment]
@EthanMarx, can you please try and `mamba install "ldas-tools-framecpp<3"` and see if that helps?

**Comment by EthanMarx** [comment]
Still seeing the same traceback. Heres the diff of `conda list` before and after running `mamba install "ldas-tools-framecpp<3"`
inside the `gwpy-3.0.5` env
```
44c44
< ldas-tools-framecpp       3.0.2                ha63f0ea_1    conda-forge
---
> ldas-tools-framecpp       2.9.2                hb003108_0    conda-forge
99c99
< python-ldas-tools-framecpp 3.0.0            py39hdd85611_0    conda-forge
---
> python-ldas-tools-framecpp 2.6.14           py39h4661b88_2    conda-forge
```

**Comment by duncanmmacleod** [comment]
Thanks, can you also confirm what host you are on when you run the `.get()`?

**Comment by EthanMarx** [comment]
I'm running the command on LHO pcdev5, 
`GWDATAFIND_SERVER=10.21.201.15:80`

**Comment by duncanmmacleod** [comment]
From my laptop (i.e. relying on NDS2) neither version works for me right now. Will try again after Tuesday maintenance.

**Comment by EthanMarx** [comment]
Interesting, I imagine the `gwpy-2.1.5` version is succeeding in reading from disk then. Thanks Duncan

**Comment by duncanmmacleod** [comment]
For that time interval, there are six (6) corresponding `H1_HOFT_C01` GWF data files that contain data for the `DCS-CALIB_STRAIN_C01` channel. However, four (4) of them declare that channel with a unit of `strain`, and the other two (2) with a unit of `''` (the empty string):

```console
$ FrDump -d 4 -i $(python3 -m gwdatafind -o H -t H1_HOFT_C01 -s 1244704476 -e 1244724476 -n 2>/dev/null) | grep DCS-CALIB_STRAIN_C01 | grep unitY | sort | uniq -c
    256   Vector:H1:DCS-CALIB_STRAIN_C01 ndata=1048576 unitY=strain unitX=  startX=0 dx=6.10352e-05
    128   Vector:H1:DCS-CALIB_STRAIN_C01 ndata=1048576 unitY= unitX=  startX=0 dx=6.10352e-05
```

This means that GWpy 3.0.5 ends up with this:

```pytb
$ python3 -c "from gwpy.timeseries import TimeSeries; print(TimeSeries.find('H1:DCS-CALIB_STRAIN_CLEAN_C01', 1244704476.0, 1244724476.0, verbose=True))"
Determined best frametype as 'H1_HOFT_C01'
Reading H1_HOFT_C01 frames: |███████████████████████████████████████████████████| 6/6 (100%) ETA 00:00
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/timeseries/core.py", line 529, in find
    return cls.DictClass.find(
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/timeseries/core.py", line 1289, in find
    new = cls.read(cache, names, start=start, end=end, pad=pad,
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/timeseries/core.py", line 908, in read
    return timeseries_reader(cls, source, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/timeseries/io/core.py", line 50, in read
    return io_read_multi(joiner, cls, source, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/io/mp.py", line 101, in read_multi
    return flatten(out)
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/timeseries/io/core.py", line 62, in _join
    out.append(tsd, gap=gap, pad=pad)
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/timeseries/core.py", line 963, in append
    self[key].append(series, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/types/series.py", line 787, in append
    self.is_compatible(other)
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/types/series.py", line 662, in is_compatible
    return self._is_compatible_gwpy(other)
  File "/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/gwpy/types/series.py", line 721, in _is_compatible_gwpy
    raise self._compatibility_error(other, "unit", "units")
ValueError: TimeSeries units do not match: strain vs
```

GWpy 2.x seems to be less discerning when it comes to 'incompatible' units, but I will need to dig deeper to work out why. Unfortunately I'm out on leave for the rest of the next two weeks, so this won't be fixed immediately.

**Comment by EthanMarx** [comment]
Okay no worries thanks Duncan!

Mostly concerned since I would expect `DCS-ANALYSIS_READY_C01:1` segments to have data that, is in fact, "analysis ready", so odd that some frames don't have proper units. Do you know if it's possible to detect this behavior _before_ querying the data?

**Comment by duncanmmacleod** [comment]
> Do you know if it's possible to detect this behavior before querying the data?

No, this is only contained within the GWF files themselves.

**Comment by EthanMarx** [comment]
Lastly, is this indicative that the data should not be used, or is the frame simply missing a unit for some reason? In other words, is it problematic that gwpy 2.1.5 is returning properly?

**Comment by EthanMarx** [comment]
The issue stems from the following in the `gwpy.detectors.units` module.

in `gwpy` 2.1.5 the `strain` unit is defined as follows:
`units.def_unit('strain', represents=units.Unit(''), namespace=_ns)`

while in `gwpy` 3.0.5 its defined as:
`units.def_unit('strain', namespace=_ns)`

I'm not sure which is the desired behavior. Its unclear to me whether frames with units set as "empty string" should be treated as useable data, or if this is mean to signify something like a data quality problem

**Comment by EthanMarx** [comment]
Upon further digging, it appears [this](https://github.com/gwpy/gwpy/commit/b30a09ccb8af338e391d844f757d674457fd6c69) commit was made to allow operations like
```
Units("strain") * Units("s") 
```
to maintain `CompositeUnit` status (i.e. will return `strain * s` as opposed to just `s` that is returned when `Units("strain")` represents `dimensionless_unscaled`)

However, this change is what leads to the above problem, since 
```
Units("strain") == Units("")
```
will evaluate to `False`, and thus `gwpy` will declare them incompatible.

**Comment by EthanMarx** [comment]
Hi @duncanmmacleod, any further ideas on this? Thanks!

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1655, please join us on gitlab to continue your contribution!
