### ISSUE TITLE
Cannot import TimeSeries: No module named 'scipy.optimize._root'

### ISSUE THREAD

**Issue by sophiehourihane** [gwpy/gwpy#1706]
This likely is just some versioning with scipy. These are the versions I have 

```
scipy                     1.10.1          py310h240c617_2    conda-forge
gwpy                      3.0.7              pyhd8ed1ab_0    conda-forge
```

And here is my traceback 
```
Traceback (most recent call last):
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/bin/bayeswave_post.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/sophie/src/BayesWave_Cpp/bayeswave-cpp/bayeswavecpp_bindings/bayeswave_post.py", line 9, in <module>
    import bayeswavecpp_bindings.bayeswave_post_utils as utils
  File "/Users/sophie/src/BayesWave_Cpp/bayeswave-cpp/bayeswavecpp_bindings/__init__.py", line 18, in <module>
    from .bayeswave_post import *
  File "/Users/sophie/src/BayesWave_Cpp/bayeswave-cpp/bayeswavecpp_bindings/bayeswave_post.py", line 12, in <module>
    from gwpy.timeseries import TimeSeries
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/gwpy/timeseries/__init__.py", line 23, in <module>
    from .timeseries import (TimeSeries, TimeSeriesDict, TimeSeriesList)
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/gwpy/timeseries/timeseries.py", line 27, in <module>
    from scipy import signal
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/scipy/__init__.py", line 200, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/scipy/signal/__init__.py", line 323, in <module>
    from ._filter_design import *
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/scipy/signal/_filter_design.py", line 16, in <module>
    from scipy import special, optimize, fft as sp_fft
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/scipy/__init__.py", line 200, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 406, in <module>
    from ._root import *
ModuleNotFoundError: No module named 'scipy.optimize._root'
```

**Comment by duncanmmacleod** [comment]
Can you post the full output of `conda list` for that environment?

And also, just to be sure, does `python3 -c "from scipy import signal"` work?

**Comment by sophiehourihane** [comment]
Oof unfortunately I just fixed it by upgrading scipy so I don't have exactly the old environment anymore. When I was in the environment `from scipy import signal` by itself did not work (outside of importing from gwpy).

**Comment by sophiehourihane** [comment]
``` 
# packages in environment at /Users/sophie/mambaforge/envs/bwcpp_env_103023:
#
# Name                    Version                   Build  Channel
astropy                   5.3.4           py310h7b7cdfe_0
autodiff                  1.0.1           py310h4eff753_0    conda-forge
bayeswavecpp-bindings     0.0.dev0                  dev_0    <develop>
blas                      1.0                    openblas
blosc                     1.21.3               hcec6c5f_0
boost                     1.78.0          py310h3e792ce_4    conda-forge
boost-cpp                 1.78.0               h2f2b2fd_4    conda-forge
brotli                    1.1.0                h0dc2134_1    conda-forge
brotli-bin                1.1.0                h0dc2134_1    conda-forge
brotli-python             1.0.9           py310h7a76584_8    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.20.1               h10d778d_1    conda-forge
c-blosc2                  2.8.0                hcec6c5f_0
c-compiler                1.5.2                hbf74d83_0    conda-forge
ca-certificates           2023.08.22           hecd8cb5_0
catch2                    3.4.0                h1c7c39f_0    conda-forge
cctools                   973.0.1             h76f1dac_13    conda-forge
cctools_osx-64            973.0.1             hcc6d90d_13    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h6c40b1e_3
cfitsio                   4.1.0                h2c97ad1_0    conda-forge
charset-normalizer        3.3.1              pyhd8ed1ab_0    conda-forge
clang                     14.0.6               h694c41f_0    conda-forge
clang-14                  14.0.6          default_h55ffa42_0    conda-forge
clang-format              14.0.6          default_h55ffa42_0    conda-forge
clang-format-14           14.0.6          default_h55ffa42_0    conda-forge
clang-tools               14.0.6          default_h55ffa42_0    conda-forge
clang_osx-64              14.0.6               h3113cd8_6    conda-forge
clangxx                   14.0.6          default_h55ffa42_0    conda-forge
clangxx_osx-64            14.0.6               h6f97653_6    conda-forge
cmake                     3.26.3               h4032537_0    conda-forge
compiler-rt               14.0.6               h613da45_0    conda-forge
compiler-rt_osx-64        14.0.6               hab78ec2_0    conda-forge
contourpy                 1.0.7           py310ha23aa8a_0    conda-forge
cppyy                     3.0.0                    pypi_0    pypi
cppyy-backend             1.14.11                  pypi_0    pypi
cppyy-cling               6.28.0                   pypi_0    pypi
cpycppyy                  1.12.13                  pypi_0    pypi
cryptography              41.0.3          py310h30e54ef_0
cxx-compiler              1.5.2                hb8565cd_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dqsegdb2                  1.2.1              pyhd8ed1ab_0    conda-forge
eigen                     3.4.0                h940c156_0    conda-forge
expat                     2.5.0                hf0c8a7f_1    conda-forge
ezdag                     0.2.0              pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          nompi_h4fa670e_108    conda-forge
fonttools                 4.43.1          py310hb372a2b_0    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
gsl                       2.7                  h93259b0_0    conda-forge
gwdatafind                1.1.3              pyhd8ed1ab_0    conda-forge
gwosc                     0.7.1              pyhd8ed1ab_0    conda-forge
gwpy                      3.0.7              pyhd8ed1ab_0    conda-forge
h5py                      3.9.0           py310hf9d4033_0
hdf5                      1.12.1               ha01d115_3
htcondor-classads         10.6.0               h59b5378_0    conda-forge
icu                       73.2                 hf5e326d_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
igwn-auth-utils           1.1.0              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4           py310ha23aa8a_1    conda-forge
krb5                      1.20.1               h049b76e_0    conda-forge
lalinference-data         3.0.3                h694c41f_0    conda-forge
lalpulsar-data            4.0.0                h694c41f_2    conda-forge
lalsimulation-data        3.1.2                h694c41f_1    conda-forge
lcms2                     2.15                 h2dcdeff_1    conda-forge
ld64                      609                 hc6ad406_13    conda-forge
ld64_osx-64               609                 hfd63004_13    conda-forge
ldas-tools-al             2.6.7                h5095954_4    conda-forge
ldas-tools-framecpp       2.9.2                h7221f53_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libaec                    1.0.6                hf0c8a7f_1    conda-forge
libblas                   3.9.0           19_osx64_openblas    conda-forge
libbrotlicommon           1.1.0                h0dc2134_1    conda-forge
libbrotlidec              1.1.0                h0dc2134_1    conda-forge
libbrotlienc              1.1.0                h0dc2134_1    conda-forge
libcblas                  3.9.0           19_osx64_openblas    conda-forge
libclang                  14.0.6          default_h55ffa42_0    conda-forge
libclang-cpp14            14.0.6          default_h55ffa42_0    conda-forge
libclang13                14.0.6          default_hb5731bd_0    conda-forge
libcondor_utils           10.6.0               he425dc9_0    conda-forge
libcurl                   7.88.1               h6df9250_1    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.18                 hac1461d_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libframel                 8.42.3               h10d778d_0    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_1    conda-forge
libgfortran5              13.2.0               h2873a65_1    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
libjpeg-turbo             2.1.5.1              h0dc2134_1    conda-forge
liblal                    7.1.7           fftw_h292f3b3_100    conda-forge
liblalburst               1.5.12               h12663b2_0    conda-forge
liblalframe               2.0.0                hac89ed1_1    conda-forge
liblalinference           3.0.3                h9a09a7d_0    conda-forge
liblalinspiral            2.0.6                h12663b2_0    conda-forge
liblalmetaio              2.1.2                hac89ed1_1    conda-forge
liblalpulsar              4.0.0                h45b5eec_2    conda-forge
liblalsimulation          3.1.2                h289410f_1    conda-forge
liblapack                 3.9.0           19_osx64_openblas    conda-forge
libllvm14                 14.0.6               h5b596cc_1    conda-forge
libllvm9                  9.0.1           default_h2671707_7    conda-forge
libmetaio                 8.5.1             ha978bb4_1002    conda-forge
libnghttp2                1.52.0               he2ab024_0    conda-forge
libopenblas               0.3.24          openmp_h48a4ad5_0    conda-forge
libpng                    1.6.39               ha978bb4_0    conda-forge
libsqlite                 3.43.2               h92b6c6a_0    conda-forge
libssh2                   1.11.0               hd019ec5_0    conda-forge
libtiff                   4.5.0                hedf67fa_6    conda-forge
libuv                     1.46.0               h0c2f820_0    conda-forge
libwebp-base              1.3.2                h0dc2134_0    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
ligo-segments             1.4.0           py310h6729b98_5    conda-forge
ligotimegps               2.0.1                      py_0    conda-forge
llvm-openmp               17.0.3               hb6ac08f_0    conda-forge
llvm-tools                14.0.6               h5b596cc_1    conda-forge
lz4-c                     1.9.4                hcec6c5f_0
lzo                       2.10                 haf1e3a3_2
make                      4.3                  h22f3db7_1    conda-forge
matplotlib                3.8.0           py310h2ec42d9_2    conda-forge
matplotlib-base           3.8.0           py310hb47e01b_0
metaio                    8.5.1             hb7f2c08_1002    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  hf0c8a7f_0    conda-forge
numexpr                   2.8.7           py310hf6dca73_0
numpy                     1.24.2          py310h788a5b3_0    conda-forge
openjpeg                  2.5.0                h13ac156_2    conda-forge
openssl                   3.1.4                hd75f5a5_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.0.0           py310hecf8f37_0    conda-forge
pcre2                     10.40                h1c4e4bc_0    conda-forge
pillow                    9.5.0           py310hd63a8c7_1    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pkg-config                0.29.2            ha3d46e9_1008    conda-forge
platformdirs              3.11.0             pyhd8ed1ab_0    conda-forge
pooch                     1.8.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
py-cpuinfo                9.0.0           py310hecd8cb5_0
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycparser                 2.21               pyhd3eb1b0_0
pyerfa                    2.0.0           py310hca72f7f_0
pyjwt                     2.4.0           py310hecd8cb5_0
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.8.0           py310h0b11676_3
python                    3.10.13         h00d2728_0_cpython    conda-forge
python-clang              14.0.6          default_hccd1708_1    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-htcondor           10.6.0          py310h5080afc_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py310h6c40b1e_0
rapidjson                 1.1.0             hb1e8313_1002    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rhash                     1.4.3                h0dc2134_2    conda-forge
safe-netrc                1.0.0                      py_0    conda-forge
scipy                     1.11.3          py310h2db466d_1    conda-forge
scitokens                 1.7.4              pyhd8ed1ab_0    conda-forge
scitokens-cpp             0.7.2                h665ca0d_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
sigtool                   0.1.3                h88f4db0_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tapi                      1100.0.11            h9ce4665_0    conda-forge
tk                        8.6.13               hef22860_0    conda-forge
tornado                   6.3.3           py310h6729b98_1    conda-forge
tqdm                      4.65.0          py310h20db666_0
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unicodedata2              15.1.0          py310h6729b98_0    conda-forge
urllib3                   2.0.7              pyhd8ed1ab_0    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                haf1e3a3_0
zlib                      1.2.13               h8a1eda9_5    conda-forge
zlib-ng                   2.0.7                h6c40b1e_0
zstd                      1.5.5                h829000d_0    conda-forge

```

Here is the (now working) environment.

**Comment by sophiehourihane** [comment]
Ah ok I ran into the same issue on the clusters when i installed gwpy after installing scipy. 

``` 
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
astropy                   5.3.4           py310h1f7b6fc_2    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
autodiff                  1.0.3           py310h64a2142_1    conda-forge
bayeswavecpp-bindings     0.0.dev0                  dev_0    <develop>
binutils                  2.40                 hdd6e379_0    conda-forge
binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
binutils_linux-64         2.40                 hbdbef99_2    conda-forge
blosc                     1.21.5               h0f2a231_0    conda-forge
boost                     1.78.0          py310hcb52e73_5    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.20.1               hd590300_1    conda-forge
c-blosc2                  2.10.5               hb4ffafa_0    conda-forge
c-compiler                1.6.0                hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
catch2                    3.4.0                h00ab1b0_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h2fee648_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
clang                     16.0.6               ha0738ec_1    conda-forge
clang-16                  16.0.6          default_h1cdf331_1    conda-forge
clang-format              16.0.6          default_h1cdf331_1    conda-forge
clang-format-16           16.0.6          default_h1cdf331_1    conda-forge
clang-tools               16.0.6          default_h1cdf331_1    conda-forge
cmake                     3.26.4               hcfe8598_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1           py310hd41b1e2_1    conda-forge
cppyy                     3.0.0                    pypi_0    pypi
cppyy-backend             1.14.11                  pypi_0    pypi
cppyy-cling               6.28.0                   pypi_0    pypi
cpycppyy                  1.12.13                  pypi_0    pypi
cryptography              41.0.5          py310h75e40e8_0    conda-forge
cxx-compiler              1.6.0                h00ab1b0_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
dqsegdb2                  1.2.1              pyhd8ed1ab_0    conda-forge
eigen                     3.4.0                h00ab1b0_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
ezdag                     0.2.0              pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          nompi_hc118613_108    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.43.1          py310h2372a71_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gcc                       12.3.0               h8d2909c_2    conda-forge
gcc_impl_linux-64         12.3.0               he2b93b0_2    conda-forge
gcc_linux-64              12.3.0               h76fc315_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.78.0               hfc55251_0    conda-forge
glib-tools                2.78.0               hfc55251_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gsoap                     2.8.123              h8dc497d_0    conda-forge
gst-plugins-base          1.22.3               h938bd60_1    conda-forge
gstreamer                 1.22.3               h977cf35_1    conda-forge
gwdatafind                1.1.3              pyhd8ed1ab_0    conda-forge
gwosc                     0.7.1              pyhd8ed1ab_0    conda-forge
gwpy                      3.0.7              pyhd8ed1ab_0    conda-forge
gxx                       12.3.0               h8d2909c_2    conda-forge
gxx_impl_linux-64         12.3.0               he2b93b0_2    conda-forge
gxx_linux-64              12.3.0               h8a814eb_2    conda-forge
h5py                      3.9.0           nompi_py310hcca72df_101    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hdf5                      1.14.1          nompi_h4f84152_100    conda-forge
htcondor-classads         10.6.0               he155508_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
igwn-auth-utils           1.1.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py310hd41b1e2_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lalinference-data         4.1.3                ha770c72_1    conda-forge
lalsimulation-data        5.2.1                ha770c72_1    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 h7f713cb_2    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
ldas-tools-al             2.6.7                h59595ed_5    conda-forge
ldas-tools-framecpp       2.9.2                hb003108_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libblas                   3.9.0           19_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           19_linux64_openblas    conda-forge
libclang                  16.0.6          default_h1cdf331_1    conda-forge
libclang-cpp16            16.0.6          default_h1cdf331_1    conda-forge
libclang13                16.0.6          default_h4d60ac6_1    conda-forge
libcondor_utils           10.6.0               hd75029c_0    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libframel                 8.42.3               hd590300_0    conda-forge
libgcc-devel_linux-64     12.3.0               h8bca6fd_2    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgfortran-ng            13.2.0               h69a702a_2    conda-forge
libgfortran5              13.2.0               ha4646dd_2    conda-forge
libglib                   2.78.0               hebfc3b9_0    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libgpg-error              1.47                 h71f35ed_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              hd590300_1    conda-forge
liblal                    7.3.1           fftw_h648628b_101    conda-forge
liblalburst               2.0.1                hc5c143e_0    conda-forge
liblalframe               3.0.1                h0b41bf4_0    conda-forge
liblalinference           4.1.3                h0c602a9_1    conda-forge
liblalinspiral            4.0.2                h0c602a9_0    conda-forge
liblalmetaio              4.0.1                h0b41bf4_0    conda-forge
liblalsimulation          5.2.1           py310h63a0205_1    conda-forge
liblapack                 3.9.0           19_linux64_openblas    conda-forge
libllvm16                 16.0.6               h5cf9203_2    conda-forge
libllvm9                  9.0.1           default_hc23dcda_7    conda-forge
libmetaio                 8.5.1             h753d276_1002    conda-forge
libnghttp2                1.55.1               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.3                 hbcd7760_1    conda-forge
libsanitizer              12.3.0               h0f45ef3_2    conda-forge
libsndfile                1.2.2                hc60ed4a_1    conda-forge
libsqlite                 3.43.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-devel_linux-64  12.3.0               h8bca6fd_2    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libsystemd0               254                  h3516f8a_0    conda-forge
libtiff                   4.6.0                h29866fb_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.46.0               hd590300_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxkbcommon              1.6.0                h5d7e998_0    conda-forge
libxml2                   2.11.5               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ligo-segments             1.4.0           py310h2372a71_5    conda-forge
ligotimegps               2.0.1                      py_0    conda-forge
llvm-openmp               17.0.3               h4dfa4b3_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
matplotlib                3.8.0           py310hff52083_2    conda-forge
matplotlib-base           3.8.0           py310h62c0568_2    conda-forge
mpg123                    1.32.3               h59595ed_0    conda-forge
munge                     0.5.13               h1c5bbd1_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.33               hf1915f5_5    conda-forge
mysql-libs                8.0.33               hca2cd23_5    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.94                 h1d7d5a4_0    conda-forge
numexpr                   2.8.7           py310hc2d3c2e_104    conda-forge
numpy                     1.26.0          py310hb13e2d6_0    conda-forge
openjpeg                  2.5.0                h488ebb8_3    conda-forge
openssl                   3.1.4                hd590300_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.2           py310hcc13569_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pillow                    10.0.1          py310h29da1c1_1    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h59595ed_0    conda-forge
pkg-config                0.29.2            h36c2ea0_1008    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulseaudio-client         16.1                 hb77b528_5    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.1.1         py310h1f7b6fc_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py310h04931ad_5    conda-forge
pyqt5-sip                 12.12.2         py310hc6cd4ac_5    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.8.0           py310ha028ce3_2    conda-forge
pytest                    7.4.3              pyhd8ed1ab_0    conda-forge
python                    3.10.13         hd12c33a_0_cpython    conda-forge
python-clang              16.0.6          default_hccd1708_1    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-htcondor           10.6.0          py310h96428ee_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py310h2372a71_1    conda-forge
qt-main                   5.15.8              h01ceb2d_12    conda-forge
rapidjson                 1.1.0             he1b5a44_1002    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rhash                     1.4.3                hd590300_2    conda-forge
safe-netrc                1.0.0                      py_0    conda-forge
scipy                     1.11.3          py310hb13e2d6_1    conda-forge
scitokens                 1.7.4              pyhd8ed1ab_0    conda-forge
scitokens-cpp             0.7.3                haea88ab_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
sip                       6.7.12          py310hc6cd4ac_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py310h2372a71_1    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unicodedata2              15.1.0          py310h2372a71_0    conda-forge
urllib3                   2.0.7              pyhd8ed1ab_0    conda-forge
voms                      2.1.0rc3             h25bd2b9_0    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xkeyboard-config          2.40                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zlib-ng                   2.0.7                h0b41bf4_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

here is the environment and yes it does seem to be a scipy issue. 
``` 
(bw_cpp_env_103123) [sophie.hourihane@ldas-pcdev1 draw_from_prior_test_110223]$ python3 -c "from scipy import signal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/site-packages/scipy/__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/site-packages/scipy/signal/__init__.py", line 324, in <module>
    from ._bsplines import *
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/site-packages/scipy/signal/_bsplines.py", line 12, in <module>
    from scipy.interpolate import BSpline
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/site-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 12, in <module>
    from . import _fitpack_py
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/site-packages/scipy/interpolate/_fitpack_py.py", line 10, in <module>
    from ._bsplines import BSpline
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/site-packages/scipy/interpolate/_bsplines.py", line 9, in <module>
    from scipy.optimize import minimize_scalar
  File "/home/sophie.hourihane/.conda/envs/bw_cpp_env_103123/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 411, in <module>
    from ._root import *
ModuleNotFoundError: No module named 'scipy.optimize._root'
```

**Comment by sophiehourihane** [comment]
Ah now I am confused because it looks like the same version of scipy and gwpy between the working env on my computer and the broken env on the cluster..

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1706, please join us on gitlab to continue your contribution!
