### ISSUE TITLE
gwpy qtransform UnboundLocalError when run on all zero timeseries. 

### ISSUE THREAD

**Issue by sophiehourihane** [gwpy/gwpy#1707]
``` 
import numpy as np 
from gwpy.timeseries import TimeSeries


times = np.arange(0, 4, 1/2048)
data = np.zeros(len(times))


time_series = TimeSeries(data, times=times)
qspecgram = time_series.q_transform(whiten=False)
```

returns 
``` 
>>> qspecgram = time_series.q_transform(whiten=False)
/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/astropy/units/quantity.py:666: RuntimeWarning: invalid value encountered in divide
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/gwpy/timeseries/timeseries.py", line 2369, in q_transform
    qgram, _ = qtransform.q_scan(
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/gwpy/signal/qtransform.py", line 689, in q_scan
    qgram, N = QTiling(duration, sampling, mismatch=mismatch, qrange=qrange,
  File "/Users/sophie/mambaforge/envs/bwcpp_env_103023/lib/python3.10/site-packages/gwpy/signal/qtransform.py", line 200, in transform
    return (out, nind * weight / nplanes)
UnboundLocalError: local variable 'out' referenced before assignment
```

Ideally i think it should return a qgram of all zeros.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1707, please join us on gitlab to continue your contribution!
