### ISSUE TITLE
TimeSeries attribute 'epoch' bug when reading from pyCBC

### ISSUE THREAD

**Issue by tjmassin** [gwpy/gwpy#191]
When trying to read in strain data from pyCBC using the TimeSeries.from_pycbc method, I found the following error:

```Traceback (most recent call last):
  File "blip-waveform.py", line 39, in <module>
    template = TimeSeries.from_pycbc(hp)
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwpy/timeseries/timeseries.py", line 1472, in from_pycbc
    return cls(ts.data, epoch=ts.epoch, sample_rate=1/ts.delta_t)
AttributeError: 'TimeSeries' object has no attribute 'epoch'```

**Comment by duncanmmacleod** [comment]
this was fixed by #194
