### ISSUE TITLE
Failures starting up gwpy

### ISSUE THREAD

**Issue by keflavich** [gwpy/gwpy#459]
I tried running the first example and immediately hit this:
```
$ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gwpy.timeseries import TimeSeries
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/gwpy/timeseries/__init__.py", line 23, in <module>
    from .timeseries import *
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/gwpy/timeseries/timeseries.py", line 37, in <module>
    from ..segments import Segment
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/gwpy/segments/__init__.py", line 26, in <module>
    from .segments import (Segment, SegmentList, SegmentListDict)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/gwpy/segments/segments.py", line 27, in <module>
    from glue.segments import (segment, segmentlist, segmentlistdict)
ImportError: No module named 'glue.segments'
>>>
```

I have the latest development version of http://glueviz.org/en/stable/

**Comment by duncanmmacleod** [comment]
@keflavich, this is a problem with multiple packages with the same namespace name. The `glue` package requried by `gwpy` is this one:

https://pypi.python.org/pypi/lscsoft-glue/

and not either of these:

https://pypi.python.org/pypi/glue/
https://pypi.python.org/pypi/glueviz/

I think this is something we're working on in LIGO at the moment, but I don't have a good workaround for now.
