### ISSUE TITLE
TimeSeries.psd median average method doesn't understand window='hanning'

### ISSUE THREAD

**Issue by hagabbar** [gwpy/gwpy#495]
When trying to do the following while whitening a time series

```python
>>> white_strain = data.whiten(16, overlap=8, method=‘median’)
Traceback (most recent call last):
  File "target_timeseries_features.py", line 58, in <module>
    white_strain = data.whiten(16, overlap=8, method='median')
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/timeseries.py", line 1544, in whiten
    method=method, window=window, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/timeseries.py", line 381, in asd
    overlap=overlap, **kwargs) ** (1/2.)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/timeseries.py", line 352, in psd
    psd_ = method_func(self, nfft, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/frequencyseries/lal_.py", line 217, in _spectrum
    return lal_psd(*args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/deps.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/frequencyseries/lal_.py", line 156, in lal_psd
    dtype=timeseries.dtype)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/frequencyseries/lal_.py", line 111, in generate_lal_window
    create = getattr(lal, 'Create%s%sWindow' % (wtype, laltype))
AttributeError: 'module' object has no attribute 'CreateHanningREAL8Window'
```

It appears that the 'median' average method is provided by LAL, and it doesn't know what 'hanning' means.

**Comment by duncanmmacleod** [comment]
This will likely be fixed by a coming PR that improves the handling of window in `gwpy.signal`.
