### ISSUE TITLE
Faulty "lal.utils import CacheEntry", should be "from glue.lal import CacheEntry"

### ISSUE THREAD

**Issue by cjhaster** [gwpy/gwpy#501]
When loading gwpy with a build of LALSuite (from the lalinference_o2 branch) made today, the gwpy loading fails with the following error

````python
>>> import gwpy.timeseries as ts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/timeseries/__init__.py", line 22, in <module>
    from .core import *
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 51, in <module>
    from ..types import (Array2D, Series)
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/types/__init__.py", line 26, in <module>
    from .array import *
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/types/array.py", line 36, in <module>
    from ..detector import Channel
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/detector/__init__.py", line 29, in <module>
    from .channel import *
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/detector/channel.py", line 36, in <module>
    from ..io import (datafind, nds2 as io_nds2)
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/io/datafind.py", line 27, in <module>
    from .gwf import (num_channels, channel_in_frame)
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/io/gwf.py", line 24, in <module>
    from .cache import open_cache
  File "/Users/cjhaster/miniconda2/envs/idp/lib/python2.7/site-packages/gwpy/io/cache.py", line 43, in <module>
    from lal.utils import CacheEntry
```

If I in the `gwpy/io/cache.py` substitute the "faulty" line with `from glue.lal import CacheEntry` everything loads, and works fine.

**Comment by duncanmmacleod** [comment]
@cjhaster, I don't see an error in the traceback you posted. `lal.utils.CacheEntry` was included in the most recent release of LAL.

**Comment by duncanmmacleod** [comment]
@cjhaster, I haven't seen a reponse on this, so will close, feel free to reopen/repost if you want.
