### ISSUE TITLE
cli: example fails on 58a68a

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#68]
On the current `HEAD` of the GWpy repository, the CLI example `cli-spg-01.png` fails to build as follows:

```
$ make ../build/sphinx/cli_examples/cli-spg-01.png
cli-spg-01
Traceback (most recent call last):
  File "../bin/gwpy-plot", line 118, in <module>
    result_code = prod.makePlot(args)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/cli/cliproduct.py", line 797, in makePlot
    self.gen_plot(args)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/cli/spectrogram.py", line 94, in gen_plot
    snr_nfft = self.dur / (secpfft * stride)
NameError: global name 'stride' is not defined
make: *** [../build/sphinx/cli_examples/cli-spg-01.png] Error 1
```

@areeda, can you take a look?

**Comment by areeda** [comment]
This is strange.  That works on my system and stride was refactored into stride_sec suggesting something didn't get committed or pushed or merged properly.

I'm on it
