### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (725,) (724,) (725,)

### ISSUE THREAD

**Issue by WuShichao** [gwpy/gwpy#696]
I'm using q_transform() to process some data, some of them are fine, but some return this error, how to fix this? I have searched the problem on Internet, for example, https://stackoverflow.com/questions/24560298/python-numpy-valueerror-operands-could-not-be-broadcast-together-with-shapes 
Is it caused by numpy?

Traceback (most recent call last):
  File "/home/nightwing/vmsync/astrop/gw/sn/programs/1/signal_data/plot.py", line 40, in <module>
    qspecgram = data.q_transform()
  File "/home/nightwing/anaconda3/lib/python3.6/site-packages/gwpy/timeseries/timeseries.py", line 1563, in q_transform
    wdata = self.whiten(fftlength, overlap, asd=whiten)
  File "/home/nightwing/anaconda3/lib/python3.6/site-packages/gwpy/timeseries/timeseries.py", line 1369, in whiten
    out.value[x:y] += npfft.irfft(in_.fft().value * invasd)
ValueError: operands could not be broadcast together with shapes (725,) (724,) (725,)

**Comment by duncanmmacleod** [comment]
Apologies for the lack of response, I hope this is fixed for you. If not, please reopen.
