### ISSUE TITLE
ModuleNotFoundError: No module named 'lal' and problem installing lal

### ISSUE THREAD

**Issue by mhaz** [gwpy/gwpy#718]
I installed gwpy with `sudo pip install gwpy[all]`
I installed root from the AUR https://aur.archlinux.org/packages/root/

In order to get started I want to try to run gwpy/examples/signal/gw150914.py 

I run `python gw150914.py `
and I get: 
`Traceback (most recent call last):
  File "gw150914.py", line 36, in <module>
    from gwpy.timeseries import TimeSeries
  File "/usr/lib/python3.6/site-packages/gwpy/timeseries/__init__.py", line 22, in <module>
    from .core import (TimeSeriesBase, TimeSeriesBaseDict, TimeSeriesBaseList)
  File "/usr/lib/python3.6/site-packages/gwpy/timeseries/core.py", line 54, in <module>
    from ..types import (Array2D, Series)
  File "/usr/lib/python3.6/site-packages/gwpy/types/__init__.py", line 26, in <module>
    from .array import *
  File "/usr/lib/python3.6/site-packages/gwpy/types/array.py", line 37, in <module>
    from ..detector import Channel
  File "/usr/lib/python3.6/site-packages/gwpy/detector/__init__.py", line 27, in <module>
    from .channel import (Channel, ChannelList)
  File "/usr/lib/python3.6/site-packages/gwpy/detector/channel.py", line 35, in <module>
    from ..io import (datafind, nds2 as io_nds2)
  File "/usr/lib/python3.6/site-packages/gwpy/io/datafind.py", line 29, in <module>
    from .cache import cache_segments
  File "/usr/lib/python3.6/site-packages/gwpy/io/cache.py", line 38, in <module>
    from lal.utils import CacheEntry
ModuleNotFoundError: No module named 'lal'`

This is the problem mentionned in https://github.com/gwpy/gwpy/issues/73
Although `sudo pip install -q http://software.ligo.org/lscsoft/source/glue-1.58.2.tar.gz
` runs without error, the issue is not solved.

I then try to install `lal` from https://pypi.python.org/pypi/lal
I download the file and I run ` pip install lal-0.0.2-cp27-cp27mu-manylinux1_x86_64.whl ` 
This gives the error
`lal-0.0.2-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.`

Installing `lalcore` from https://aur.archlinux.org/packages/lalcore/ does not solve the issue.
With `lalcore` I get the error
`Traceback (most recent call last):
  File "gw150914.py", line 36, in <module>
    from gwpy.timeseries import TimeSeries
  File "/usr/lib/python3.6/site-packages/gwpy/timeseries/__init__.py", line 22, in <module>
    from .core import (TimeSeriesBase, TimeSeriesBaseDict, TimeSeriesBaseList)
  File "/usr/lib/python3.6/site-packages/gwpy/timeseries/core.py", line 54, in <module>
    from ..types import (Array2D, Series)
  File "/usr/lib/python3.6/site-packages/gwpy/types/__init__.py", line 26, in <module>
    from .array import *
  File "/usr/lib/python3.6/site-packages/gwpy/types/array.py", line 37, in <module>
    from ..detector import Channel
  File "/usr/lib/python3.6/site-packages/gwpy/detector/__init__.py", line 27, in <module>
    from .channel import (Channel, ChannelList)
  File "/usr/lib/python3.6/site-packages/gwpy/detector/channel.py", line 35, in <module>
    from ..io import (datafind, nds2 as io_nds2)
  File "/usr/lib/python3.6/site-packages/gwpy/io/datafind.py", line 28, in <module>
    from ..time import to_gps
  File "/usr/lib/python3.6/site-packages/gwpy/time/__init__.py", line 34, in <module>
    from lal import LIGOTimeGPS
  File "/usr/lib/python3.6/site-packages/lal/__init__.py", line 23, in <module>
    cached_detector_by_prefix = dict((cd.frDetector.prefix, cd) for cd in CachedDetectors)
NameError: name 'CachedDetectors' is not defined`
Which I don't know how to troubleshoot.

Then I try to follow the instructions from https://wiki.ligo.org/DASWG/LALSuiteInstall

`checking for FRAMECPPC... no`
`checking for FrameCFileOpen in -lframecppc... no`
`checking framecppc/FrameC.h usability... no`
`checking framecppc/FrameC.h presence... no`
`checking for framecppc/FrameC.h... no`
`checking for LIBFRAME... no`
`checking for FrLibIni in -lFrame... no`
`checking FrameL.h usability... no`
`checking FrameL.h presence... no`
`checking for FrameL.h... no`
`configure: error: no frame library available`
`configure: error: ./configure failed for lalframe`

I guess I should install http://lappweb.in2p3.fr/virgo/FrameL/ but I rather ask for advice before going too deep without fully understanding what I am doing.

**Comment by mhaz** [comment]
I installed lalsuite from https://pypi.python.org/pypi/lalsuite/6.48.1.dev20180313 and this was enough to display some plots.
I still get errors like
`Traceback (most recent call last):
  File "gw150914.py", line 122, in <module>
    lfilt.shift('6.9ms')
  File "/usr/lib/python3.6/site-packages/gwpy/types/array.py", line 188, in __getattr__
    return super(Array, self).__getattribute__(attr)
AttributeError: 'TimeSeries' object has no attribute 'shift'` 
But I guess the issue discussed in this thread is not relevant anymore.

**Comment by duncanmmacleod** [comment]
@mhaz, apologies for the delay in responding to this, I've been out at a meeting for the last two weeks. What you found is a problem related to the latest release of [`lscsoft-glue`](//pypi.org/project/lscsoft-glue) which depends on (but doesn't declare that dependency on) `lal`. The easiest solution is exactly what you discovered, to `pip install lalsuite`.

I will look into the best solution such that `pip install gwpy` gives you code that works properly out-of-the-box.

The other issue of the `AttributeError` is just that gwpy-0.9.0 introduces a new method `TimeSeries.shift`, and you don't seem to have that version installed (likely gwpy-0.8.1). If you `pip install gwpy --upgrade`, that should do the trick.

**Comment by mhaz** [comment]
@duncanmmacleod Thank you for the explication. I will upgrade to gwpy-0.9.0
