### ISSUE TITLE
Error "AttributeError: 'module' object has no attribute 'Show'"

### ISSUE THREAD

**Issue by yuzuri** [gwpy/gwpy#937]
I faced the error when I tried to show the plot.
The error message : 
``` shell
Traceback (most recent call last):
  File "plot_BLRMS_m31.py", line 27, in <module>
    plot.show()
  File "/home/somewhere/local/pip/lib/python2.7/site-packages/gwpy/plot/plot.py", line 281, in show
    backend_mod.Show().mainloop()
AttributeError: 'module' object has no attribute 'Show'
```

A part of the code :
``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from gwpy.timeseries import TimeSeries
from gwpy.time import tconvert
....
data = TimeSeries.read("cache.txt", ch, start=gps_beg, end=gps_end, nproc=4, verbose=True)
data_filtered = data.lowpass(f_high).highpass(f_low)
data_RMS = data_filtered.rms(1)
plot = data_RMS.plot()
plot.show()
plot.savefig("hoge.png")
```

The problem is caused by calling `plot.show()`.
If you know the solution and you need the additional information, please let me know.

**Comment by duncanmmacleod** [comment]
thanks @yuzuri, before I forget, this was generated using the `GtkAgg` backend.
